### PR TITLE
Ninapro regression

### PR DESCRIPTION
**Pull request by AmirRezaHariri**
NinaPro DB2 support added. Different features such as filtering and feature extraction tested to work with both regression flag on and off. Default regression (dataglove) is False so old codes should work without the need to change. Preferably merge into a new branch if more test is required.

### CODE REVIEW

**Review by cbmorrell — CHANGES_REQUESTED** [review]
We definitely want to add support for dataglove info, but I don't think we need to change things like the `OfflineDataHandler` and `Filter`. Adding support for the cyberglove should mostly be localized to the `NinaproDB2` dataset class.

With this in mind, any changes to general classes like `OfflineDataHandler` and `Filter` shouldn't have dataset-specific flags/parameters. The only thing I see that needs changed is maybe adding a way to filter info other than raw EMG (e.g., dataglove info), but that also isn't being done here. 

From what I can tell, all of these changes can be implemented without changing those classes. Suggested changes:

- The changes to `Filter` are just indexing into data to ensure only EMG data are filtered. Instead, the dataglove data should be stored as a separate parameter and the `data` parameter should only store EMG, which can already be done by setting `data_column` when parsing.
- Similarly, the changes to `parse_windows` just returns the EMG and dataglove info separately by indexing into the EMG data structure. Instead, dataglove data should be in a separate field and you should specify how you want to parse it via the `metadata_operations` parameter. See this showcase for an example of that: https://github.com/LibEMG/LibEMG_OfflineRegression_Showcase.
-  A `dataset` parameter was also added to the `OfflineDataHandler` but it is never used.

Adding the option to parse cyberglove data is good for the `NinaproDB2` class, so the changes there should be kept. Just change `prepare_data` so it separates cyberglove and EMG into separate fields and it should be good. Also, make sure to add documentation for any new parameters you add.

**Comment by AmirRezaHariri** [comment]
So basically, adding something like the `OfflineDataHandler` to `prepare_data`, to have a fully independent dataglove dataset seperate from EMG raw data?

**Comment by cbmorrell** [comment]
> So basically, adding something like the `OfflineDataHandler` to `prepare_data`, to have a fully independent dataglove dataset seperate from EMG raw data?

@AmirRezaHariri Not 100% sure what you mean here. It should all be stored in the `OfflineDataHandler` that is returned by `prepare_data`. I'm suggesting that you change how data are stored in the `OfflineDataHandler` so EMG data is stored in `data` and cyberglove labels are stored in another field. I haven't tested this code, so your mileage may vary, but you could try something like this:

```python
regex_filters = [
    RegexFilter(left_bound = "/C", right_bound="R", values = classes_values, description='classes'),
    RegexFilter(left_bound = "R", right_bound=".csv", values = reps_values, description='reps'),
    RegexFilter(left_bound="DB2_s", right_bound="/",values=subjects_values, description='subjects')
]
metadata_fetchers = [
    ColumnFetcher('cyberglove', column_mask=[idx for idx in range(self.EMG_LEN, self.EMG_LEN + self.DATAGLOVE_LEN)])
]
emg_column_mask = [idx for idx in range(self.EMG_LEN)]
odh = OfflineDataHandler()
odh.get_data(folder_location=self.dataset_folder, regex_filters=regex_filters, metadata_fetchers=metadata_fetchers, delimiter=",", data_column=emg_column_mask)
return odh
```

This way you create a mask to grab the cyberglove data and store that in a `cyberglove` parameter, then create a separate mask just to grab EMG data. Then you can parse the `cyberglove` data however you want. If you wanted to just take the last value within that window, for example, you could do this: `odh.parse_windows(window_size, window_inc, metadata_operations={'cyberglove': 'last_sample'})`.

**Comment by AmirRezaHariri** [comment]
@cbmorrell got it.

**Review by cbmorrell — APPROVED** [review]
Looks good to me. Just need to add documentation about what the `dataglove` parameter does in `NinaproDB2` then it should be good to go.

**Pull request merged**
